# Generated by Django 3.0.8 on 2020-07-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callednumber',
            name='number',
            field=models.CharField(max_length=50),
        ),
    ]
