# Generated by Django 3.0.8 on 2020-07-12 17:44

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_carduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='b',
            field=django_mysql.models.ListTextField(models.CharField(max_length=50), size=None),
        ),
        migrations.AlterField(
            model_name='card',
            name='g',
            field=django_mysql.models.ListTextField(models.CharField(max_length=50), size=None),
        ),
        migrations.AlterField(
            model_name='card',
            name='i',
            field=django_mysql.models.ListTextField(models.CharField(max_length=50), size=None),
        ),
        migrations.AlterField(
            model_name='card',
            name='n',
            field=django_mysql.models.ListTextField(models.CharField(max_length=50), size=None),
        ),
        migrations.AlterField(
            model_name='card',
            name='o',
            field=django_mysql.models.ListTextField(models.CharField(max_length=50), size=None),
        ),
    ]
