# Generated by Django 3.0.8 on 2020-07-11 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingoAuth', '0002_user_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='card',
        ),
    ]
