# Generated by Django 3.0.8 on 2020-08-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0002_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasActive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
