# Generated by Django 3.0.8 on 2020-07-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=10)),
                ('group_name', models.CharField(max_length=20)),
            ],
        ),
    ]
