# Generated by Django 3.0.8 on 2020-07-09 20:19

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', django_mysql.models.ListTextField(models.IntegerField(), size=None)),
                ('i', django_mysql.models.ListTextField(models.IntegerField(), size=None)),
                ('n', django_mysql.models.ListTextField(models.IntegerField(), size=None)),
                ('g', django_mysql.models.ListTextField(models.IntegerField(), size=None)),
                ('o', django_mysql.models.ListTextField(models.IntegerField(), size=None)),
            ],
        ),
    ]
