# Generated by Django 3.0.8 on 2020-07-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingoAuth', '0005_auto_20200711_1339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
