# Generated by Django 3.0.8 on 2020-07-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingoAuth', '0007_bingouser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BingoUser',
        ),
    ]
